dist: xenial

addons:
  postgresql: "9.6"
  # TODO: Add mysql addon as well

services:
  - postgresql

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  global:
    - POSTGRESQL_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    - REQUIREMENTS=release EXTRAS=all,postgresql,tests SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release EXTRAS=all,sqlite,tests

python:
  - "3.6"
  - "3.7"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"
  - mkdir /tmp/elasticsearch
  - wget -O - $ES6_DOWNLOAD_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - sleep 10

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

# check if release tag is the same as version.py tag
before_deploy:
- |-
  SRCTAG=$(find . -name "version.py" | grep -v 'build' | grep -v '.eggs' | xargs cat | grep '__version__' | sed 's/__version__//' | sed 's/=//g' | sed 's/"//g' | sed "s/'//g" | sed 's/[ \t\n]//g')
  echo "Version string in sources is $SRCTAG, travis version is $TRAVIS_TAG"
  test $SRCTAG == $TRAVIS_TAG

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "dyU00BHuC6VZ+2rUEOQy8I4ULZa9TcTUOLyyDm/VAz8vSC5TfEzifMh85+35fGa1tkM8mTstzfsF+veazChWxd16acfdrYaaqLIagc1Wofjp8ndCWSl6lrmp30coaoLBEVGi3/hSEpEAcjzuyq7gljIPLFXAvIsLVPQ01NvIIzdcV5gUlH9W4MqUoohiYbK6XJeBFqay6YW4NVH/yyH8ifrZMmbWDmoFkko+axVXZUO5h73ui9VVY2fMPIZKdXcD0hpYf0n7nP/Nxrtiy5HSkVogJca27k2oL+X0Y87gGxkHesTzuyJp1CoWaR3wSAIp8f7uJpUUfMZd+hlLG/K/8zef/lbh/lrptNWDZAhJTSK1CKpkKiej0ZiTrMP4zzKjLd+vC5jt9DcnHDqr/XK1BQgBqC3xMf+wqY9192ZLS+jjbt4pjamrLqb/giqU6nBhG/hEbVDLbDJqtTFsH474BuA9Gwbpk/0T/DLtv3CRXahUrp6qgWiyKSenu1oeAuOBJXJGvw4behwi8ZH5ONdVAb2+HYuH0Tcyb8TWDHRGFC0fCCNdGpE9bw1lIHRhQUX1C1GwUwwdjmz1Wm8AGdsk7tStksW36iyw4dB7ZOCHezO1GAE6EIyPvDEai0mkCMhgHXTOSRjqXGnbbfiog1NcVOFSuIeDVCo/LjytRsN1FZs="
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true
